spring:
  application:
    name: journaly
  data:
    mongodb:
      uri: mongodb+srv://USRRID:PASSWORD@CLUSTER.l5xu1gp.mongodb.net/?retryWrites=true&w=majority&appName=AnantClus
      database: journaldb
      auto-index-creation: true


server:
  port: 8080
#spring:
#  data:
#    mongodb:
#      username: journalyUser
#      password: journalyPassword
